### ISSUE TITLE
Crash on non-file templates

### ISSUE THREAD

**Issue by rfleschenberg** [nedbat/django_coverage_plugin#1]
Thanks for writing this, Ned. I think it's a great idea and a very useful tool to have. So I get to file the first issue on it ;)

django-coverage-plugin crashes on templates that don't have an underlying file. For example, this view:

    from django.template import Template, Context
    from django.http import HttpResponse

    def i_am_broken(request):
        tpl = Template(u"Hello!")
        return HttpResponse(tpl.render(Context({})))

And this test:
```
from django.test import TestCase


class MyTest(TestCase):

    def test_request(self):
        response = self.client.get('/broken/')
        self.assertEquals(response.content, 'Hello!')
```

Traceback:
```
Traceback (most recent call last):
  File "/var/tmp/coveragetest/coveragetest/tests.py", line 7, in test_request
    response = self.client.get('/broken/')
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django/test/client.py", line 470, in get
    **extra)
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django/test/client.py", line 286, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django/test/client.py", line 358, in generic
    return self.request(**r)
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django/test/client.py", line 422, in request
    response = self.handler(environ)
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/tmp/coveragetest/coveragetest/views.py", line 7, in i_am_broken
    return HttpResponse(tpl.render(Context({})))
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django/template/base.py", line 870, in render
    return self.s
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django/template/base.py", line 870, in render
    return self.s
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/coverage/pytracer.py", line 112, in _trace
    lineno_from, lineno_to = self.file_tracer.line_number_range(frame)
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django_coverage_plugin/plugin.py", line 80, in line_number_range
    line_map = self.get_line_map(source[0].name)
  File "/home/rene/.virtualenvs/coveragtest/lib/python2.7/site-packages/django_coverage_plugin/plugin.py", line 102, in get_line_map
    with open(filename) as template_file:
IOError: [Errno 2] No such file or directory: u'<unknown source>'
```

**Comment by nedbat** [comment]
Fixed in 4c77643.
