### ISSUE TITLE
Django 2.1a1: cannot import name 'TOKEN_BLOCK'

### ISSUE THREAD

**Issue by stefankoegl** [nedbat/django_coverage_plugin#51]
When trying to run my project with [Django 2.1a1](https://www.djangoproject.com/weblog/2018/may/17/django-21-alpha-1/), I get the following error

````
envdir envs/dev/ pytest --cov=mygpo/ --cov-branch
Traceback (most recent call last):
  File "/home/stefan/mygpo/venv/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/config.py", line 49, in main
    config = _prepareconfig(args, plugins)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/config.py", line 168, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/config.py", line 957, in pytest_cmdline_parse
    self.parse(args)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/config.py", line 1121, in parse
    self._preparse(args, addopts=addopts)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/config.py", line 1092, in _preparse
    args=args, parser=self._parser)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/pytest_cov/plugin.py", line 97, in pytest_load_initial_conftests
    plugin = CovPlugin(early_config.known_args_namespace, early_config.pluginmanager)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/pytest_cov/plugin.py", line 152, in __init__
    self.start(engine.Central)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/pytest_cov/plugin.py", line 174, in start
    self.cov_controller.start()
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/pytest_cov/engine.py", line 146, in start
    self.cov.erase()
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/coverage/control.py", line 726, in erase
    self._init()
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/coverage/control.py", line 226, in _init
    self.plugins = Plugins.load_plugins(self.config.plugins, self.config, self.debug)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/coverage/plugin_support.py", line 40, in load_plugins
    __import__(module)
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/django_coverage_plugin/__init__.py", line 6, in <module>
    from .plugin import DjangoTemplatePlugin
  File "/home/stefan/mygpo/venv/lib/python3.5/site-packages/django_coverage_plugin/plugin.py", line 16, in <module>
    from django.template.base import (
ImportError: cannot import name 'TOKEN_BLOCK'
````

I did not find anything in the (under development) [release notes](https://docs.djangoproject.com/en/dev/releases/2.1/). Is this something that should be addressed in django_coverage_plugin, or should I report it to django instead?

**Comment by clokep** [comment]
Looks like django/django#9938 replaced this and related constants with an enum.

**Comment by Fandekasp** [comment]
Same issue
```
$ docker-compose run backend coverage run --source='.' /usr/local/bin/pytest  
Starting infrastructure_db_1 ... done
Traceback (most recent call last):
  File "/usr/local/bin/coverage", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/coverage/cmdline.py", line 753, in main
    status = CoverageScript().command_line(argv)
  File "/usr/local/lib/python3.7/site-packages/coverage/cmdline.py", line 488, in command_line
    return self.do_run(options, args)
  File "/usr/local/lib/python3.7/site-packages/coverage/cmdline.py", line 617, in do_run
    self.coverage.erase()
  File "/usr/local/lib/python3.7/site-packages/coverage/control.py", line 726, in erase
    self._init()
  File "/usr/local/lib/python3.7/site-packages/coverage/control.py", line 226, in _init
    self.plugins = Plugins.load_plugins(self.config.plugins, self.config, self.debug)
  File "/usr/local/lib/python3.7/site-packages/coverage/plugin_support.py", line 40, in load_plugins
    __import__(module)
  File "/usr/local/lib/python3.7/site-packages/django_coverage_plugin/__init__.py", line 6, in <module>
    from .plugin import DjangoTemplatePlugin
  File "/usr/local/lib/python3.7/site-packages/django_coverage_plugin/plugin.py", line 16, in <module>
    from django.template.base import (
ImportError: cannot import name 'TOKEN_BLOCK' from 'django.template.base' (/usr/local/lib/python3.7/site-packages/django/template/base.py)
```

Django==2.1
django-coverage-plugin==1.5.0

**Comment by jambonrose** [comment]
Now that #57 has been merged into master, this issue is now fixed.

I will be releasing the latest version later today.

Thanks to all of you for documenting the issue!

**Comment by jambonrose** [comment]
I have issued a release-candidate with the changes: https://pypi.org/project/django_coverage_plugin/1.6rc1/
